services:
  - type: web
    name: inventory-system-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://wynson30:Wynson050916*@cluster0.y5mroum.mongodb.net/inventory-system?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://inventory-system-front-wyn.vercel.app,https://inventory-system-front-wine.vercel.app 